image: python:alpine

test:
  stage: test
  script:
    - pip install flake8
    - flake8 --config=tox.ini .

production:
  type: deploy
  environment: production
  script:
    - apk add --no-cache ruby ruby-rdoc ruby-irb curl ca-certificates git
    - gem install dpl --no-doc
    - dpl --provider=heroku --api-key=$HEROKU_PRODUCTION_API_KEY --app=$HEROKU_APP_NAME
  only:
    - tags