stages:
  - build

#####################################################
#                common steps                       #
#####################################################
.shared_hidden_key: &build_anchor
  image: docker:latest
  tags:
    - docker
  services:
    - docker:dind
  before_script:
    - docker version
    - docker info
    - docker login -u $CI_BUILD_LOGIN -p $CI_BUILD_TOKEN $CI_REGISTRY
  after_script:
    - docker logout $CI_REGISTRY

#####################################################
#                 build docker image                #
#####################################################
build_staging:
  stage: build
  <<: *build_anchor
  script:
    - docker build -t ${CI_REGISTRY}/${CI_PROJECT_PATH}:latest --pull .
    - docker push ${CI_REGISTRY}/${CI_PROJECT_PATH}:latest